image: node:16

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - public

pages:
  stage: deploy
  script:
    - mv public/ public/  # Pas besoin de bouger quoi que ce soit si tout est déjà dans public
  artifacts:
    paths:
      - public
  only:
    - main  # Change selon ta branche principale si besoin
