image: node:16  # Utilise l'image Docker officielle de Node.js

stages:
  - build       # Première étape : construire l'application
  - deploy      # Deuxième étape : déployer sur GitLab Pages

cache:
  paths:
    - node_modules/  # Cache les dépendances Node.js pour accélérer les futurs builds

build:
  stage: build
  script:
    - npm install        # Installe les dépendances Node.js (Three.js, Vite, etc.)
    - npm run build      # Exécute la build avec Vite, qui génère les fichiers dans 'public/'
  artifacts:
    paths:
      - public           # Sauvegarde le dossier 'public/' pour l'étape suivante
