image: node:16

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - public

pages:
  stage: deploy
  artifacts:
    paths:
      - public
  only:
    - main  # Remplace par ta branche principale si nécessaire
